version: '3'
services:
  bittorrent:
    image: zakkg3/bittorrent
  # uncomment for build  build: .
    restart: always
    ports:
      - 8080:80 # Main access.
      - 5050:5000 # Incoming peer traffic.
      - 6060:6881 # Incoming/outgoing DHT traffic.
    volumes:
      - /home/nico/torrent/data:/data/rtorrent # Content directory.
